/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PlatformType = IDL.Variant({
  'wordpress_woo' : IDL.Null,
  'otherPlatform' : IDL.Null,
  'shopify' : IDL.Null,
});
export const PlatformConnection = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'apiKey' : IDL.Text,
  'apiSecret' : IDL.Text,
  'platformType' : PlatformType,
});
export const PersonalAccount = IDL.Record({
  'nid' : IDL.Text,
  'taxId' : IDL.Text,
  'password' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'transfer_out' : IDL.Null,
  'deposit' : IDL.Null,
  'transfer_in' : IDL.Null,
  'withdrawal' : IDL.Null,
  'funding' : IDL.Null,
  'cash_out' : IDL.Record({
    'destination' : IDL.Text,
    'provider' : IDL.Variant({
      'upay' : IDL.Null,
      'payoneer' : IDL.Null,
      'nagad' : IDL.Null,
      'bkash' : IDL.Null,
      'rocket' : IDL.Null,
      'paypal' : IDL.Null,
    }),
  }),
});
export const Currency = IDL.Variant({
  'bdt' : IDL.Null,
  'btc' : IDL.Null,
  'eth' : IDL.Null,
  'usd' : IDL.Null,
  'other' : IDL.Text,
  'usdt' : IDL.Variant({
    'op' : IDL.Null,
    'bnb' : IDL.Null,
    'etc' : IDL.Null,
    'eth' : IDL.Null,
    'star' : IDL.Null,
  }),
});
export const Time = IDL.Int;
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'status' : TransactionStatus,
  'transactionType' : TransactionType,
  'owner' : IDL.Principal,
  'reference' : IDL.Opt(IDL.Text),
  'sender' : IDL.Opt(IDL.Principal),
  'currency' : Currency,
  'timestamp' : Time,
  'amount' : IDL.Nat,
  'receiver' : IDL.Opt(IDL.Principal),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const WalletBalance = IDL.Record({
  'currency' : Currency,
  'amount' : IDL.Nat,
});
export const PaymentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'status' : PaymentStatus,
  'description' : IDL.Text,
  'currency' : IDL.Text,
  'payee' : IDL.Principal,
  'payer' : IDL.Principal,
  'amount' : IDL.Nat,
});
export const CashOutRequest = IDL.Record({
  'destination' : IDL.Text,
  'provider' : IDL.Variant({
    'upay' : IDL.Null,
    'payoneer' : IDL.Null,
    'nagad' : IDL.Null,
    'bkash' : IDL.Null,
    'rocket' : IDL.Null,
    'paypal' : IDL.Null,
  }),
  'reference' : IDL.Opt(IDL.Text),
  'currency' : Currency,
  'amount' : IDL.Nat,
});
export const InternalTransferRequest = IDL.Record({
  'recipient' : IDL.Principal,
  'reference' : IDL.Opt(IDL.Text),
  'currency' : Currency,
  'amount' : IDL.Nat,
});
export const InternalTransferRequestByPhone = IDL.Record({
  'reference' : IDL.Opt(IDL.Text),
  'currency' : Currency,
  'phoneNumber' : IDL.Text,
  'amount' : IDL.Nat,
});
export const FundingRequest = IDL.Record({
  'method' : IDL.Variant({
    'visa' : IDL.Record({
      'cvv' : IDL.Text,
      'card_number' : IDL.Text,
      'card_holder' : IDL.Text,
      'expiry' : IDL.Text,
    }),
    'mastercard' : IDL.Record({
      'cvv' : IDL.Text,
      'card_number' : IDL.Text,
      'card_holder' : IDL.Text,
      'expiry' : IDL.Text,
    }),
    'bank_account' : IDL.Record({
      'bank_name' : IDL.Text,
      'account_number' : IDL.Text,
      'account_holder' : IDL.Text,
      'routing_number' : IDL.Text,
    }),
  }),
  'reference' : IDL.Opt(IDL.Text),
  'currency' : Currency,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createConnection' : IDL.Func(
      [IDL.Text, PlatformType, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createPayment' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createPaymentByPhone' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteConnection' : IDL.Func([IDL.Nat], [], []),
  'getCallerConnections' : IDL.Func(
      [],
      [IDL.Vec(PlatformConnection)],
      ['query'],
    ),
  'getCallerPersonalAccount' : IDL.Func(
      [],
      [IDL.Opt(PersonalAccount)],
      ['query'],
    ),
  'getCallerTransactionHistory' : IDL.Func(
      [],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerWalletBalance' : IDL.Func([], [IDL.Vec(WalletBalance)], ['query']),
  'getConnection' : IDL.Func([IDL.Nat], [PlatformConnection], ['query']),
  'getPayment' : IDL.Func([IDL.Nat], [Payment], ['query']),
  'getPersonalAccount' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PersonalAccount)],
      ['query'],
    ),
  'getTransactionHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserAccount' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'walletBalances' : IDL.Opt(IDL.Vec(WalletBalance)),
          'personalAccount' : IDL.Opt(PersonalAccount),
          'transactions' : IDL.Opt(IDL.Vec(Transaction)),
          'profile' : IDL.Opt(UserProfile),
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWalletBalance' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(WalletBalance)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'listAllUsers' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'principal' : IDL.Principal,
            'personalAccount' : IDL.Opt(PersonalAccount),
            'profile' : IDL.Opt(UserProfile),
          })
        ),
      ],
      ['query'],
    ),
  'listPaymentsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Payment)],
      ['query'],
    ),
  'processCashOut' : IDL.Func([CashOutRequest], [IDL.Nat], []),
  'processInternalTransfer' : IDL.Func(
      [InternalTransferRequest],
      [IDL.Nat],
      [],
    ),
  'processInternalTransferByPhone' : IDL.Func(
      [InternalTransferRequestByPhone],
      [IDL.Nat],
      [],
    ),
  'resendAddMoneyOtp' : IDL.Func([IDL.Nat], [], []),
  'saveCallerPersonalAccount' : IDL.Func([PersonalAccount], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startAddMoney' : IDL.Func([FundingRequest], [IDL.Nat], []),
  'updateConnection' : IDL.Func(
      [IDL.Nat, IDL.Text, PlatformType, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
  'verifyAddMoney' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PlatformType = IDL.Variant({
    'wordpress_woo' : IDL.Null,
    'otherPlatform' : IDL.Null,
    'shopify' : IDL.Null,
  });
  const PlatformConnection = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'apiKey' : IDL.Text,
    'apiSecret' : IDL.Text,
    'platformType' : PlatformType,
  });
  const PersonalAccount = IDL.Record({
    'nid' : IDL.Text,
    'taxId' : IDL.Text,
    'password' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'transfer_out' : IDL.Null,
    'deposit' : IDL.Null,
    'transfer_in' : IDL.Null,
    'withdrawal' : IDL.Null,
    'funding' : IDL.Null,
    'cash_out' : IDL.Record({
      'destination' : IDL.Text,
      'provider' : IDL.Variant({
        'upay' : IDL.Null,
        'payoneer' : IDL.Null,
        'nagad' : IDL.Null,
        'bkash' : IDL.Null,
        'rocket' : IDL.Null,
        'paypal' : IDL.Null,
      }),
    }),
  });
  const Currency = IDL.Variant({
    'bdt' : IDL.Null,
    'btc' : IDL.Null,
    'eth' : IDL.Null,
    'usd' : IDL.Null,
    'other' : IDL.Text,
    'usdt' : IDL.Variant({
      'op' : IDL.Null,
      'bnb' : IDL.Null,
      'etc' : IDL.Null,
      'eth' : IDL.Null,
      'star' : IDL.Null,
    }),
  });
  const Time = IDL.Int;
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : TransactionStatus,
    'transactionType' : TransactionType,
    'owner' : IDL.Principal,
    'reference' : IDL.Opt(IDL.Text),
    'sender' : IDL.Opt(IDL.Principal),
    'currency' : Currency,
    'timestamp' : Time,
    'amount' : IDL.Nat,
    'receiver' : IDL.Opt(IDL.Principal),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const WalletBalance = IDL.Record({
    'currency' : Currency,
    'amount' : IDL.Nat,
  });
  const PaymentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'status' : PaymentStatus,
    'description' : IDL.Text,
    'currency' : IDL.Text,
    'payee' : IDL.Principal,
    'payer' : IDL.Principal,
    'amount' : IDL.Nat,
  });
  const CashOutRequest = IDL.Record({
    'destination' : IDL.Text,
    'provider' : IDL.Variant({
      'upay' : IDL.Null,
      'payoneer' : IDL.Null,
      'nagad' : IDL.Null,
      'bkash' : IDL.Null,
      'rocket' : IDL.Null,
      'paypal' : IDL.Null,
    }),
    'reference' : IDL.Opt(IDL.Text),
    'currency' : Currency,
    'amount' : IDL.Nat,
  });
  const InternalTransferRequest = IDL.Record({
    'recipient' : IDL.Principal,
    'reference' : IDL.Opt(IDL.Text),
    'currency' : Currency,
    'amount' : IDL.Nat,
  });
  const InternalTransferRequestByPhone = IDL.Record({
    'reference' : IDL.Opt(IDL.Text),
    'currency' : Currency,
    'phoneNumber' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const FundingRequest = IDL.Record({
    'method' : IDL.Variant({
      'visa' : IDL.Record({
        'cvv' : IDL.Text,
        'card_number' : IDL.Text,
        'card_holder' : IDL.Text,
        'expiry' : IDL.Text,
      }),
      'mastercard' : IDL.Record({
        'cvv' : IDL.Text,
        'card_number' : IDL.Text,
        'card_holder' : IDL.Text,
        'expiry' : IDL.Text,
      }),
      'bank_account' : IDL.Record({
        'bank_name' : IDL.Text,
        'account_number' : IDL.Text,
        'account_holder' : IDL.Text,
        'routing_number' : IDL.Text,
      }),
    }),
    'reference' : IDL.Opt(IDL.Text),
    'currency' : Currency,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createConnection' : IDL.Func(
        [IDL.Text, PlatformType, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createPayment' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createPaymentByPhone' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteConnection' : IDL.Func([IDL.Nat], [], []),
    'getCallerConnections' : IDL.Func(
        [],
        [IDL.Vec(PlatformConnection)],
        ['query'],
      ),
    'getCallerPersonalAccount' : IDL.Func(
        [],
        [IDL.Opt(PersonalAccount)],
        ['query'],
      ),
    'getCallerTransactionHistory' : IDL.Func(
        [],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerWalletBalance' : IDL.Func(
        [],
        [IDL.Vec(WalletBalance)],
        ['query'],
      ),
    'getConnection' : IDL.Func([IDL.Nat], [PlatformConnection], ['query']),
    'getPayment' : IDL.Func([IDL.Nat], [Payment], ['query']),
    'getPersonalAccount' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PersonalAccount)],
        ['query'],
      ),
    'getTransactionHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserAccount' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'walletBalances' : IDL.Opt(IDL.Vec(WalletBalance)),
            'personalAccount' : IDL.Opt(PersonalAccount),
            'transactions' : IDL.Opt(IDL.Vec(Transaction)),
            'profile' : IDL.Opt(UserProfile),
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWalletBalance' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(WalletBalance)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'listAllUsers' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'principal' : IDL.Principal,
              'personalAccount' : IDL.Opt(PersonalAccount),
              'profile' : IDL.Opt(UserProfile),
            })
          ),
        ],
        ['query'],
      ),
    'listPaymentsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'processCashOut' : IDL.Func([CashOutRequest], [IDL.Nat], []),
    'processInternalTransfer' : IDL.Func(
        [InternalTransferRequest],
        [IDL.Nat],
        [],
      ),
    'processInternalTransferByPhone' : IDL.Func(
        [InternalTransferRequestByPhone],
        [IDL.Nat],
        [],
      ),
    'resendAddMoneyOtp' : IDL.Func([IDL.Nat], [], []),
    'saveCallerPersonalAccount' : IDL.Func([PersonalAccount], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startAddMoney' : IDL.Func([FundingRequest], [IDL.Nat], []),
    'updateConnection' : IDL.Func(
        [IDL.Nat, IDL.Text, PlatformType, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
    'verifyAddMoney' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };