/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PlatformType = IDL.Variant({
  'wordpress_woo' : IDL.Null,
  'otherPlatform' : IDL.Null,
  'shopify' : IDL.Null,
});
export const PlatformConnection = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'apiKey' : IDL.Text,
  'apiSecret' : IDL.Text,
  'platformType' : PlatformType,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PaymentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const Payment = IDL.Record({
  'status' : PaymentStatus,
  'description' : IDL.Text,
  'currency' : IDL.Text,
  'payee' : IDL.Principal,
  'payer' : IDL.Principal,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createConnection' : IDL.Func(
      [IDL.Text, PlatformType, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createPayment' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteConnection' : IDL.Func([IDL.Nat], [], []),
  'getCallerConnections' : IDL.Func(
      [],
      [IDL.Vec(PlatformConnection)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConnection' : IDL.Func([IDL.Nat], [PlatformConnection], ['query']),
  'getPayment' : IDL.Func([IDL.Nat], [Payment], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'listPaymentsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Payment)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateConnection' : IDL.Func(
      [IDL.Nat, IDL.Text, PlatformType, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PlatformType = IDL.Variant({
    'wordpress_woo' : IDL.Null,
    'otherPlatform' : IDL.Null,
    'shopify' : IDL.Null,
  });
  const PlatformConnection = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'apiKey' : IDL.Text,
    'apiSecret' : IDL.Text,
    'platformType' : PlatformType,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PaymentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Payment = IDL.Record({
    'status' : PaymentStatus,
    'description' : IDL.Text,
    'currency' : IDL.Text,
    'payee' : IDL.Principal,
    'payer' : IDL.Principal,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createConnection' : IDL.Func(
        [IDL.Text, PlatformType, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createPayment' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteConnection' : IDL.Func([IDL.Nat], [], []),
    'getCallerConnections' : IDL.Func(
        [],
        [IDL.Vec(PlatformConnection)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConnection' : IDL.Func([IDL.Nat], [PlatformConnection], ['query']),
    'getPayment' : IDL.Func([IDL.Nat], [Payment], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'listPaymentsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateConnection' : IDL.Func(
        [IDL.Nat, IDL.Text, PlatformType, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };