/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Payment {
  'status' : PaymentStatus,
  'description' : string,
  'currency' : string,
  'payee' : Principal,
  'payer' : Principal,
  'amount' : bigint,
}
export type PaymentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null };
export interface PlatformConnection {
  'id' : bigint,
  'owner' : Principal,
  'name' : string,
  'apiKey' : string,
  'apiSecret' : string,
  'platformType' : PlatformType,
}
export type PlatformType = { 'wordpress_woo' : null } |
  { 'otherPlatform' : null } |
  { 'shopify' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createConnection' : ActorMethod<
    [string, PlatformType, string, string],
    bigint
  >,
  /**
   * / Create a new payment request with currency
   */
  'createPayment' : ActorMethod<[Principal, bigint, string, string], bigint>,
  'deleteConnection' : ActorMethod<[bigint], undefined>,
  'getCallerConnections' : ActorMethod<[], Array<PlatformConnection>>,
  /**
   * / Get the caller's user profile
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConnection' : ActorMethod<[bigint], PlatformConnection>,
  /**
   * / Get payment by id
   */
  'getPayment' : ActorMethod<[bigint], Payment>,
  /**
   * / Get a user's profile
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List all payments
   */
  'listAllPayments' : ActorMethod<[], Array<Payment>>,
  /**
   * / List all payments for a user
   */
  'listPaymentsForUser' : ActorMethod<[Principal], Array<Payment>>,
  /**
   * / Save the caller's user profile
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateConnection' : ActorMethod<
    [bigint, string, PlatformType, string, string],
    undefined
  >,
  /**
   * / Update the status of a payment
   */
  'updatePaymentStatus' : ActorMethod<[bigint, PaymentStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];