/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FundingRequest {
    method: {
        __kind__: "visa";
        visa: null;
    } | {
        __kind__: "mastercard";
        mastercard: null;
    } | {
        __kind__: "bank_account";
        bank_account: {
            account_number: string;
        };
    };
    reference?: string;
    currency: Currency;
    amount: bigint;
}
export type Time = bigint;
export interface WalletBalance {
    currency: Currency;
    amount: bigint;
}
export type Currency = {
    __kind__: "bdt";
    bdt: null;
} | {
    __kind__: "btc";
    btc: null;
} | {
    __kind__: "eth";
    eth: null;
} | {
    __kind__: "usd";
    usd: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "usdt";
    usdt: Variant_op_bnb_etc_eth_star;
};
export interface CashOutRequest {
    destination: string;
    provider: Variant_upay_payoneer_nagad_bkash_rocket_paypal;
    reference?: string;
    currency: Currency;
    amount: bigint;
}
export interface Payment {
    status: PaymentStatus;
    description: string;
    currency: string;
    payee: Principal;
    payer: Principal;
    amount: bigint;
}
export type TransactionType = {
    __kind__: "transfer_out";
    transfer_out: null;
} | {
    __kind__: "deposit";
    deposit: null;
} | {
    __kind__: "transfer_in";
    transfer_in: null;
} | {
    __kind__: "withdrawal";
    withdrawal: null;
} | {
    __kind__: "funding";
    funding: null;
} | {
    __kind__: "cash_out";
    cash_out: {
        destination: string;
        provider: Variant_upay_payoneer_nagad_bkash_rocket_paypal;
    };
};
export interface Transaction {
    id: bigint;
    status: TransactionStatus;
    transactionType: TransactionType;
    owner: Principal;
    reference?: string;
    sender?: Principal;
    currency: Currency;
    timestamp: Time;
    amount: bigint;
    receiver?: Principal;
}
export interface PlatformConnection {
    id: bigint;
    owner: Principal;
    name: string;
    apiKey: string;
    apiSecret: string;
    platformType: PlatformType;
}
export interface PersonalAccount {
    nid: string;
    taxId: string;
    password: string;
    fullName: string;
    email: string;
    address: string;
    phone: string;
}
export interface InternalTransferRequest {
    recipient: Principal;
    reference?: string;
    currency: Currency;
    amount: bigint;
}
export interface UserProfile {
    name: string;
}
export enum PaymentStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed"
}
export enum PlatformType {
    wordpress_woo = "wordpress_woo",
    otherPlatform = "otherPlatform",
    shopify = "shopify"
}
export enum TransactionStatus {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_op_bnb_etc_eth_star {
    op = "op",
    bnb = "bnb",
    etc = "etc",
    eth = "eth",
    star = "star"
}
export enum Variant_upay_payoneer_nagad_bkash_rocket_paypal {
    upay = "upay",
    payoneer = "payoneer",
    nagad = "nagad",
    bkash = "bkash",
    rocket = "rocket",
    paypal = "paypal"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createConnection(name: string, platformType: PlatformType, apiKey: string, apiSecret: string): Promise<bigint>;
    createPayment(payee: Principal, amount: bigint, currency: string, description: string): Promise<bigint>;
    deleteConnection(id: bigint): Promise<void>;
    getCallerConnections(): Promise<Array<PlatformConnection>>;
    getCallerPersonalAccount(): Promise<PersonalAccount | null>;
    getCallerTransactionHistory(): Promise<Array<Transaction>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCallerWalletBalance(): Promise<Array<WalletBalance>>;
    getConnection(id: bigint): Promise<PlatformConnection>;
    getPayment(id: bigint): Promise<Payment>;
    getPersonalAccount(user: Principal): Promise<PersonalAccount | null>;
    getTransactionHistory(user: Principal): Promise<Array<Transaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWalletBalance(user: Principal): Promise<Array<WalletBalance>>;
    isCallerAdmin(): Promise<boolean>;
    listAllPayments(): Promise<Array<Payment>>;
    listPaymentsForUser(user: Principal): Promise<Array<Payment>>;
    processAddMoney(request: FundingRequest): Promise<bigint>;
    processCashOut(request: CashOutRequest): Promise<bigint>;
    processInternalTransfer(transfer: InternalTransferRequest): Promise<bigint>;
    saveCallerPersonalAccount(account: PersonalAccount): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateConnection(id: bigint, name: string, platformType: PlatformType, apiKey: string, apiSecret: string): Promise<void>;
    updatePaymentStatus(id: bigint, status: PaymentStatus): Promise<void>;
}
import type { CashOutRequest as _CashOutRequest, Currency as _Currency, FundingRequest as _FundingRequest, InternalTransferRequest as _InternalTransferRequest, Payment as _Payment, PaymentStatus as _PaymentStatus, PersonalAccount as _PersonalAccount, PlatformConnection as _PlatformConnection, PlatformType as _PlatformType, Time as _Time, Transaction as _Transaction, TransactionStatus as _TransactionStatus, TransactionType as _TransactionType, UserProfile as _UserProfile, UserRole as _UserRole, WalletBalance as _WalletBalance } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createConnection(arg0: string, arg1: PlatformType, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createConnection(arg0, to_candid_PlatformType_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createConnection(arg0, to_candid_PlatformType_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async createPayment(arg0: Principal, arg1: bigint, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPayment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPayment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteConnection(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteConnection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteConnection(arg0);
            return result;
        }
    }
    async getCallerConnections(): Promise<Array<PlatformConnection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerConnections();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerConnections();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerPersonalAccount(): Promise<PersonalAccount | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPersonalAccount();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPersonalAccount();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerTransactionHistory(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerTransactionHistory();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerTransactionHistory();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerWalletBalance(): Promise<Array<WalletBalance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerWalletBalance();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerWalletBalance();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConnection(arg0: bigint): Promise<PlatformConnection> {
        if (this.processError) {
            try {
                const result = await this.actor.getConnection(arg0);
                return from_candid_PlatformConnection_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConnection(arg0);
            return from_candid_PlatformConnection_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayment(arg0: bigint): Promise<Payment> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayment(arg0);
                return from_candid_Payment_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayment(arg0);
            return from_candid_Payment_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPersonalAccount(arg0: Principal): Promise<PersonalAccount | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPersonalAccount(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPersonalAccount(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionHistory(arg0: Principal): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionHistory(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionHistory(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWalletBalance(arg0: Principal): Promise<Array<WalletBalance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWalletBalance(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWalletBalance(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllPayments();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllPayments();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPaymentsForUser(arg0: Principal): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPaymentsForUser(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPaymentsForUser(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async processAddMoney(arg0: FundingRequest): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.processAddMoney(to_candid_FundingRequest_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processAddMoney(to_candid_FundingRequest_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async processCashOut(arg0: CashOutRequest): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.processCashOut(to_candid_CashOutRequest_n42(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processCashOut(to_candid_CashOutRequest_n42(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async processInternalTransfer(arg0: InternalTransferRequest): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.processInternalTransfer(to_candid_InternalTransferRequest_n45(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processInternalTransfer(to_candid_InternalTransferRequest_n45(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerPersonalAccount(arg0: PersonalAccount): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerPersonalAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerPersonalAccount(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateConnection(arg0: bigint, arg1: string, arg2: PlatformType, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateConnection(arg0, arg1, to_candid_PlatformType_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateConnection(arg0, arg1, to_candid_PlatformType_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async updatePaymentStatus(arg0: bigint, arg1: PaymentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n47(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n47(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Currency_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Currency): Currency {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_PlatformConnection_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlatformConnection): PlatformConnection {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PlatformType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlatformType): PlatformType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionStatus): TransactionStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_WalletBalance_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WalletBalance): WalletBalance {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PersonalAccount]): PersonalAccount | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TransactionStatus;
    transactionType: _TransactionType;
    owner: Principal;
    reference: [] | [string];
    sender: [] | [Principal];
    currency: _Currency;
    timestamp: _Time;
    amount: bigint;
    receiver: [] | [Principal];
}): {
    id: bigint;
    status: TransactionStatus;
    transactionType: TransactionType;
    owner: Principal;
    reference?: string;
    sender?: Principal;
    currency: Currency;
    timestamp: Time;
    amount: bigint;
    receiver?: Principal;
} {
    return {
        id: value.id,
        status: from_candid_TransactionStatus_n14(_uploadFile, _downloadFile, value.status),
        transactionType: from_candid_TransactionType_n16(_uploadFile, _downloadFile, value.transactionType),
        owner: value.owner,
        reference: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.reference)),
        sender: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.sender)),
        currency: from_candid_Currency_n22(_uploadFile, _downloadFile, value.currency),
        timestamp: value.timestamp,
        amount: value.amount,
        receiver: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.receiver))
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    destination: string;
    provider: {
        upay: null;
    } | {
        payoneer: null;
    } | {
        nagad: null;
    } | {
        bkash: null;
    } | {
        rocket: null;
    } | {
        paypal: null;
    };
}): {
    destination: string;
    provider: Variant_upay_payoneer_nagad_bkash_rocket_paypal;
} {
    return {
        destination: value.destination,
        provider: from_candid_variant_n19(_uploadFile, _downloadFile, value.provider)
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    currency: _Currency;
    amount: bigint;
}): {
    currency: Currency;
    amount: bigint;
} {
    return {
        currency: from_candid_Currency_n22(_uploadFile, _downloadFile, value.currency),
        amount: value.amount
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PaymentStatus;
    description: string;
    currency: string;
    payee: Principal;
    payer: Principal;
    amount: bigint;
}): {
    status: PaymentStatus;
    description: string;
    currency: string;
    payee: Principal;
    payer: Principal;
    amount: bigint;
} {
    return {
        status: from_candid_PaymentStatus_n33(_uploadFile, _downloadFile, value.status),
        description: value.description,
        currency: value.currency,
        payee: value.payee,
        payer: value.payer,
        amount: value.amount
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    owner: Principal;
    name: string;
    apiKey: string;
    apiSecret: string;
    platformType: _PlatformType;
}): {
    id: bigint;
    owner: Principal;
    name: string;
    apiKey: string;
    apiSecret: string;
    platformType: PlatformType;
} {
    return {
        id: value.id,
        owner: value.owner,
        name: value.name,
        apiKey: value.apiKey,
        apiSecret: value.apiSecret,
        platformType: from_candid_PlatformType_n8(_uploadFile, _downloadFile, value.platformType)
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): TransactionStatus {
    return "pending" in value ? TransactionStatus.pending : "completed" in value ? TransactionStatus.completed : "failed" in value ? TransactionStatus.failed : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transfer_out: null;
} | {
    deposit: null;
} | {
    transfer_in: null;
} | {
    withdrawal: null;
} | {
    funding: null;
} | {
    cash_out: {
        destination: string;
        provider: {
            upay: null;
        } | {
            payoneer: null;
        } | {
            nagad: null;
        } | {
            bkash: null;
        } | {
            rocket: null;
        } | {
            paypal: null;
        };
    };
}): {
    __kind__: "transfer_out";
    transfer_out: null;
} | {
    __kind__: "deposit";
    deposit: null;
} | {
    __kind__: "transfer_in";
    transfer_in: null;
} | {
    __kind__: "withdrawal";
    withdrawal: null;
} | {
    __kind__: "funding";
    funding: null;
} | {
    __kind__: "cash_out";
    cash_out: {
        destination: string;
        provider: Variant_upay_payoneer_nagad_bkash_rocket_paypal;
    };
} {
    return "transfer_out" in value ? {
        __kind__: "transfer_out",
        transfer_out: value.transfer_out
    } : "deposit" in value ? {
        __kind__: "deposit",
        deposit: value.deposit
    } : "transfer_in" in value ? {
        __kind__: "transfer_in",
        transfer_in: value.transfer_in
    } : "withdrawal" in value ? {
        __kind__: "withdrawal",
        withdrawal: value.withdrawal
    } : "funding" in value ? {
        __kind__: "funding",
        funding: value.funding
    } : "cash_out" in value ? {
        __kind__: "cash_out",
        cash_out: from_candid_record_n18(_uploadFile, _downloadFile, value.cash_out)
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upay: null;
} | {
    payoneer: null;
} | {
    nagad: null;
} | {
    bkash: null;
} | {
    rocket: null;
} | {
    paypal: null;
}): Variant_upay_payoneer_nagad_bkash_rocket_paypal {
    return "upay" in value ? Variant_upay_payoneer_nagad_bkash_rocket_paypal.upay : "payoneer" in value ? Variant_upay_payoneer_nagad_bkash_rocket_paypal.payoneer : "nagad" in value ? Variant_upay_payoneer_nagad_bkash_rocket_paypal.nagad : "bkash" in value ? Variant_upay_payoneer_nagad_bkash_rocket_paypal.bkash : "rocket" in value ? Variant_upay_payoneer_nagad_bkash_rocket_paypal.rocket : "paypal" in value ? Variant_upay_payoneer_nagad_bkash_rocket_paypal.paypal : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bdt: null;
} | {
    btc: null;
} | {
    eth: null;
} | {
    usd: null;
} | {
    other: string;
} | {
    usdt: {
        op: null;
    } | {
        bnb: null;
    } | {
        etc: null;
    } | {
        eth: null;
    } | {
        star: null;
    };
}): {
    __kind__: "bdt";
    bdt: null;
} | {
    __kind__: "btc";
    btc: null;
} | {
    __kind__: "eth";
    eth: null;
} | {
    __kind__: "usd";
    usd: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "usdt";
    usdt: Variant_op_bnb_etc_eth_star;
} {
    return "bdt" in value ? {
        __kind__: "bdt",
        bdt: value.bdt
    } : "btc" in value ? {
        __kind__: "btc",
        btc: value.btc
    } : "eth" in value ? {
        __kind__: "eth",
        eth: value.eth
    } : "usd" in value ? {
        __kind__: "usd",
        usd: value.usd
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "usdt" in value ? {
        __kind__: "usdt",
        usdt: from_candid_variant_n24(_uploadFile, _downloadFile, value.usdt)
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    op: null;
} | {
    bnb: null;
} | {
    etc: null;
} | {
    eth: null;
} | {
    star: null;
}): Variant_op_bnb_etc_eth_star {
    return "op" in value ? Variant_op_bnb_etc_eth_star.op : "bnb" in value ? Variant_op_bnb_etc_eth_star.bnb : "etc" in value ? Variant_op_bnb_etc_eth_star.etc : "eth" in value ? Variant_op_bnb_etc_eth_star.eth : "star" in value ? Variant_op_bnb_etc_eth_star.star : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
}): PaymentStatus {
    return "cancelled" in value ? PaymentStatus.cancelled : "pending" in value ? PaymentStatus.pending : "completed" in value ? PaymentStatus.completed : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    wordpress_woo: null;
} | {
    otherPlatform: null;
} | {
    shopify: null;
}): PlatformType {
    return "wordpress_woo" in value ? PlatformType.wordpress_woo : "otherPlatform" in value ? PlatformType.otherPlatform : "shopify" in value ? PlatformType.shopify : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WalletBalance>): Array<WalletBalance> {
    return value.map((x)=>from_candid_WalletBalance_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlatformConnection>): Array<PlatformConnection> {
    return value.map((x)=>from_candid_PlatformConnection_n6(_uploadFile, _downloadFile, x));
}
function to_candid_CashOutRequest_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CashOutRequest): _CashOutRequest {
    return to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_Currency_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Currency): _Currency {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_FundingRequest_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FundingRequest): _FundingRequest {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_InternalTransferRequest_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InternalTransferRequest): _InternalTransferRequest {
    return to_candid_record_n46(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function to_candid_PlatformType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlatformType): _PlatformType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    method: {
        __kind__: "visa";
        visa: null;
    } | {
        __kind__: "mastercard";
        mastercard: null;
    } | {
        __kind__: "bank_account";
        bank_account: {
            account_number: string;
        };
    };
    reference?: string;
    currency: Currency;
    amount: bigint;
}): {
    method: {
        visa: null;
    } | {
        mastercard: null;
    } | {
        bank_account: {
            account_number: string;
        };
    };
    reference: [] | [string];
    currency: _Currency;
    amount: bigint;
} {
    return {
        method: to_candid_variant_n38(_uploadFile, _downloadFile, value.method),
        reference: value.reference ? candid_some(value.reference) : candid_none(),
        currency: to_candid_Currency_n39(_uploadFile, _downloadFile, value.currency),
        amount: value.amount
    };
}
function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    destination: string;
    provider: Variant_upay_payoneer_nagad_bkash_rocket_paypal;
    reference?: string;
    currency: Currency;
    amount: bigint;
}): {
    destination: string;
    provider: {
        upay: null;
    } | {
        payoneer: null;
    } | {
        nagad: null;
    } | {
        bkash: null;
    } | {
        rocket: null;
    } | {
        paypal: null;
    };
    reference: [] | [string];
    currency: _Currency;
    amount: bigint;
} {
    return {
        destination: value.destination,
        provider: to_candid_variant_n44(_uploadFile, _downloadFile, value.provider),
        reference: value.reference ? candid_some(value.reference) : candid_none(),
        currency: to_candid_Currency_n39(_uploadFile, _downloadFile, value.currency),
        amount: value.amount
    };
}
function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    recipient: Principal;
    reference?: string;
    currency: Currency;
    amount: bigint;
}): {
    recipient: Principal;
    reference: [] | [string];
    currency: _Currency;
    amount: bigint;
} {
    return {
        recipient: value.recipient,
        reference: value.reference ? candid_some(value.reference) : candid_none(),
        currency: to_candid_Currency_n39(_uploadFile, _downloadFile, value.currency),
        amount: value.amount
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "visa";
    visa: null;
} | {
    __kind__: "mastercard";
    mastercard: null;
} | {
    __kind__: "bank_account";
    bank_account: {
        account_number: string;
    };
}): {
    visa: null;
} | {
    mastercard: null;
} | {
    bank_account: {
        account_number: string;
    };
} {
    return value.__kind__ === "visa" ? {
        visa: value.visa
    } : value.__kind__ === "mastercard" ? {
        mastercard: value.mastercard
    } : value.__kind__ === "bank_account" ? {
        bank_account: value.bank_account
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlatformType): {
    wordpress_woo: null;
} | {
    otherPlatform: null;
} | {
    shopify: null;
} {
    return value == PlatformType.wordpress_woo ? {
        wordpress_woo: null
    } : value == PlatformType.otherPlatform ? {
        otherPlatform: null
    } : value == PlatformType.shopify ? {
        shopify: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "bdt";
    bdt: null;
} | {
    __kind__: "btc";
    btc: null;
} | {
    __kind__: "eth";
    eth: null;
} | {
    __kind__: "usd";
    usd: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "usdt";
    usdt: Variant_op_bnb_etc_eth_star;
}): {
    bdt: null;
} | {
    btc: null;
} | {
    eth: null;
} | {
    usd: null;
} | {
    other: string;
} | {
    usdt: {
        op: null;
    } | {
        bnb: null;
    } | {
        etc: null;
    } | {
        eth: null;
    } | {
        star: null;
    };
} {
    return value.__kind__ === "bdt" ? {
        bdt: value.bdt
    } : value.__kind__ === "btc" ? {
        btc: value.btc
    } : value.__kind__ === "eth" ? {
        eth: value.eth
    } : value.__kind__ === "usd" ? {
        usd: value.usd
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "usdt" ? {
        usdt: to_candid_variant_n41(_uploadFile, _downloadFile, value.usdt)
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_op_bnb_etc_eth_star): {
    op: null;
} | {
    bnb: null;
} | {
    etc: null;
} | {
    eth: null;
} | {
    star: null;
} {
    return value == Variant_op_bnb_etc_eth_star.op ? {
        op: null
    } : value == Variant_op_bnb_etc_eth_star.bnb ? {
        bnb: null
    } : value == Variant_op_bnb_etc_eth_star.etc ? {
        etc: null
    } : value == Variant_op_bnb_etc_eth_star.eth ? {
        eth: null
    } : value == Variant_op_bnb_etc_eth_star.star ? {
        star: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_upay_payoneer_nagad_bkash_rocket_paypal): {
    upay: null;
} | {
    payoneer: null;
} | {
    nagad: null;
} | {
    bkash: null;
} | {
    rocket: null;
} | {
    paypal: null;
} {
    return value == Variant_upay_payoneer_nagad_bkash_rocket_paypal.upay ? {
        upay: null
    } : value == Variant_upay_payoneer_nagad_bkash_rocket_paypal.payoneer ? {
        payoneer: null
    } : value == Variant_upay_payoneer_nagad_bkash_rocket_paypal.nagad ? {
        nagad: null
    } : value == Variant_upay_payoneer_nagad_bkash_rocket_paypal.bkash ? {
        bkash: null
    } : value == Variant_upay_payoneer_nagad_bkash_rocket_paypal.rocket ? {
        rocket: null
    } : value == Variant_upay_payoneer_nagad_bkash_rocket_paypal.paypal ? {
        paypal: null
    } : value;
}
function to_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} {
    return value == PaymentStatus.cancelled ? {
        cancelled: null
    } : value == PaymentStatus.pending ? {
        pending: null
    } : value == PaymentStatus.completed ? {
        completed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
